### ISSUE TITLE
Integration in functions/package? 

### ISSUE THREAD

**Issue by pat-s** [gaborcsardi/notifier#14]
Hi @gaborcsardi! 

I really like your notifier!! 
One of my packages deals with long runs of parallel workers and I would love to have such a notification popping up once the complete task has finished. 

Am I right that it only works in the terminal and not in RStudio? 
And as sourcing your script every time is not an option and `install_github()` does not work, do you have any suggestion how I could implement your notifier into my package?

**Comment by gaborcsardi** [comment]
> Am I right that it only works in the terminal and not in RStudio?

No, it works in RStudio as well. Or at least should.

> And as sourcing your script every time is not an option and install_github() does not work, do you have any suggestion how I could implement your notifier into my package?

Why does `install_github` not work? That should work, too.

**Comment by gaborcsardi** [comment]
If these do not work for you, please open issues, so I can fix them. Thanks!

**Comment by gaborcsardi** [comment]
Or use this issue to elaborate what you mean by "does not work". I.e. what is the error you are seeing and on what system? Thanks.

**Comment by pat-s** [comment]
`install_github()` works, just caused by a typo!

Opened another issue regarding RStudio integration: #15
