### ISSUE TITLE
`notify()` does not work in RStudio 

### ISSUE THREAD

**Issue by pat-s** [gaborcsardi/notifier#15]
`notify()` does not work in RStudio. No error message, just no notification appearing. 

In terminal everything works fine. 

* macOS 10.12.1
* R 3.3.2
* RStudio 1.0.136

**Comment by gaborcsardi** [comment]
I cannot reproduce this. Can you please try
* Installing the latest notifier from GitHub, and 
* Restarting Rstudio?

Just to eliminate the trivial mistakes... if it still does not work, please send the output of 
```r
list.files(system.file(package = "notifier"))
list.files(system.file(package = "notifier", "tn"))
```

Thanks!

**Comment by pat-s** [comment]
Reinstalled using `install_github()` and restarted RStudio. Still not working.

```R
list.files(system.file(package = "notifier"))
 [1] "DESCRIPTION"    "help"           "html"           "INDEX"          "LICENSE"        "linux.png"      "macos.png"     
 [8] "Meta"           "NAMESPACE"      "NEWS.md"        "oldwindows.png" "R"              "R.ico"          "R.png"         
[15] "tn"             "windows.png"   

list.files(system.file(package = "notifier", "tn"))
[1] "bin"                        "binary"                     "INSTALL_RECEIPT.json"       "LICENSE.md"                
[5] "README.markdown"            "terminal-notifier.app"      "terminal-notifier.app.dSYM"
```

**Comment by gaborcsardi** [comment]
Hmmm. Can you please send the output of 
```
grep -A 1 CFBundleIdentifier /Applications/RStudio.app/Contents/Info.plist
```
from a terminal? Assuming your RStudio is installed there...

**Comment by pat-s** [comment]
```bash
grep -A 1 CFBundleIdentifier /Applications/RStudio.app/Contents/Info.plist

	<key>CFBundleIdentifier</key>
	<string>org.rstudio.RStudio</string>
```

I installed RStudio using homebrew.

**Comment by gaborcsardi** [comment]
From which brew formula?

**Comment by gaborcsardi** [comment]
Btw. I think installing rstudio and/or R from homebrew is asking for trouble. These versions are not supported.

**Comment by pat-s** [comment]
`brew cask install rstudio-preview` (homebrew-versions tap https://github.com/caskroom/homebrew-versions/tree/master/Casks)
`brew cask install r` (homebrew-science tap: https://github.com/Homebrew/homebrew-science)

So you suggest to uninstall all homebrew R/RStudio installations and install the official binaries?

**Comment by pat-s** [comment]
Notification from RStudio is shown in notification center but does not pop up on screen.
May be related to security settings of RStudio somehow? 

![screenshot at dez 12 13-58-15](https://cloud.githubusercontent.com/assets/8430564/21100216/25c8242c-c073-11e6-9eaa-46786a9f1fe2.png)

**Comment by gaborcsardi** [comment]
Yes, brew installs have problems, quite often, e.g. this is a recent one: https://stat.ethz.ch/pipermail/r-sig-mac/2016-December/012126.html

Yes, I guess you need to enable RStudio in Notification Center. Maybe.

**Comment by pat-s** [comment]
Reinstalled R 3.3.2 and RStudio 1.0.44 using binaries. Notification in notification center was already set to "banner" for RStudio and R. Still no success :/

Are you also working on macOS? Strange error..

**Comment by gaborcsardi** [comment]
I am on macOS, but I don't remember what I set up in the notification center over the years. Maybe you also need to allow `terminal-notifier`, since this is the tools `notify()` is using.

**Comment by gaborcsardi** [comment]
Btw. try to call the `terminal-notifier` program directly from the command line. It is in `system.file(package = "notifier", "tn")`

**Comment by pat-s** [comment]
Calling it directly via 
```R
system("open -a /Library/Frameworks/R.framework/Versions/3.3/Resources/library/notifier/tn/terminal-notifier.app")
```
works within the Console of RStudio. Plain "Terminal" badge. 

Are you actually calling `terminal-notifier.app` or `bin/terminal-notifier` in `notify()`?

**Comment by gaborcsardi** [comment]
Here is what I am doing: https://github.com/gaborcsardi/notifier/blob/61be7579615ebf5fc1cb6b851543a815ad47e8b5/R/macos.R#L6-L7

Maybe you can check what is in `binary`. This should be the location of the binary file. But all this is the same regardless of RStudio. The only difference in RStudio is the icon: https://github.com/gaborcsardi/notifier/blob/61be7579615ebf5fc1cb6b851543a815ad47e8b5/R/macos.R#L14-L18

Maybe your OS version does not allow the icon override? Can you try it directly from the command line?

**Comment by pat-s** [comment]
Here is my `tn` path: 
(As we are calling the `terminal-notifier` within `.app`, may be the `/bin/terminal-notifier` is not needed at all?)
```R
tn
[1] "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/notifier/tn/./terminal-notifier.app/Contents/MacOS/terminal-notifier"
```

There is also this difference here:

```R
bundle_id <- if (Sys.getenv("RSTUDIO", "") == "1") {
    "org.rstudio.RStudio"
  } else {
    "org.r-project.R"
  }
```

So this could be a potential source as it works with `r-project`? 

However, of course, it could also be an macOS security issue. Assuming you are not running 10.12 Sierra?

Btw I checked it on Windows and Linux, everything smooth there 👍

**Comment by gaborcsardi** [comment]
> (As we are calling the terminal-notifier within .app, may be the /bin/terminal-notifier is not needed at all?)

homebrew puts it there, and it is harmless.

> So this could be a potential source as it works with r-project?

Yes, but why? The r-project app is faked, just as rstudio, because the notification is coming from the terminal....

> However, of course, it could also be an macOS security issue. Assuming you are not running 10.12 Sierra?

I am not, but will try on a Sierra machine later today...

**Comment by gaborcsardi** [comment]
Sorry, haven't tried sierra yet, will try again today.

**Comment by gaborcsardi** [comment]
No luck again today, the machine did not have xcode, so I could not install terminal-notifier..... :(

**Comment by pat-s** [comment]
Guess I found the problem:

Notification badge is only shown when the focus is on another application than RStudio. However your example finished so fast that I cannot switch to another application in the meantime. 

Found this after putting your package into my function which takes quite some time. 

However this only applies to RStudio on macOS for me. On Windows and Linux notification badges are shown at any time.

**Comment by gaborcsardi** [comment]
This is really strange to me. Maybe I should switch back to showing the notification from R.app then? Or maybe create an app for this purpose?

**Comment by TMCjp** [comment]
hi gaborcsardi,
when i install the package in my windows, i have a error, 

`*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -O3 -Wall  -std=gnu99 -mtune=core2 main.m AppDelegate.m -o macnotifier 

-framework AppKit -framework ScriptingBridge

gcc.exe: error: AppKit: No such file or directory

gcc.exe: error: ScriptingBridge: No such file or directory

gcc.exe: error: unrecognized command line option '-framework'

gcc.exe: error: unrecognized command line option '-framework'

make: *** [macnotifier] Error 1

Warning: 运行命令'make -f "Makevars" -f "F:/R/R-3.4.1/etc/i386/Makeconf" -f "F:/R/R-3.4.1/share/make/winshlib.mk" SHLIB="notifier.dll" SHLIB_LIBADD='$(OBJC_LIBS)' '的状态是2

ERROR: compilation failed for package 'notifier'`

`sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)`

what can i do?

**Comment by gaborcsardi** [comment]
@TMCjp this is a closed issue, and closed issues do not get attention usually. If you have problems, consider opening a new issue, please. 

Yes, unfortunately the GitHub version of the package is broken. You can install the last CRAN version like this:

```
devtools::install_version("notifier", "1.0.0")
```
