### ISSUE TITLE
CRAN release date?

### ISSUE THREAD

**Issue by pat-s** [gaborcsardi/notifier#16]
Any rough plans for a CRAN release? Would make the integration of `notify()` in my package more easy :)

**Comment by gaborcsardi** [comment]
I am a little bit worried about problems of strange platforms, and also the install process on macOS and Windows, so I want to try it on more systems.

OTH, I can just release it, and then I'll hear about the problems earlier.....

**Comment by pat-s** [comment]
You refer to the recent differing behavior of R.app and RStudio.app in #15 ? 

I plan to release a major update of [`sperrorest`](https://github.com/pat-s/sperrorest) in January. Since I already integrated `notifier` with different scenarios, it would be great if I could add this feature within this release. 

Besides the small problems in #15, everything works fine so far.

Let me know if I can help you with some testing.

**Comment by VincentGuyader** [comment]
Hi also use notifier on [https://github.com/ThinkRstat/togglr](url) a cran release wiil be a good news :)

**Comment by gaborcsardi** [comment]
So, my worry is with macOS. CRAN uses Mavericks to build packages, and I am using `brew` to install / build the notifier app on macOS. But brew does not support Mavericks any more. Neither does Apple, actually. 

So I'll need to test it with Mavericks first. Let me give it a try.

**Comment by gaborcsardi** [comment]
MAvericks seems to work fine.....

**Comment by gaborcsardi** [comment]
OK, submitted.

**Comment by gaborcsardi** [comment]
It is on CRAN now, we'll see if it will be OK on the various CRAN platforms.
