### ISSUE TITLE
Removed from CRAN?

### ISSUE THREAD

**Issue by pat-s** [gaborcsardi/notifier#18]
Why was `notifier` removed from CRAN again? https://cran.r-project.org/web/packages/notifier/index.html

I just submitted my package, which uses `notifier`, to CRAN and ran into some problems - especially on win-builder: 

> "You managed to hang up my whole check machine as you 
> apparently start a program notifu.exe and do not stop it at the end of 
> the checks. This caused winbuilder to hang during the auto-incoming 
> check" 

Is it related to this issue? 

So I guess I have to remove it again from my package?

**Comment by gaborcsardi** [comment]
Yes, calling external programs from R is tricky, and especially tricky on CRAN.

I'll rewrite the macOS part in objective C, so no external programs are needed for that, but it is not possible with windows.

**Comment by pat-s** [comment]
What a pity. If I would have simply skipped all `notifier()` tests, no problems would have occurred. 

So then I'll have to remove the `notify()` feature again from my package :/

**Comment by VincentGuyader** [comment]
snif' :(

**Comment by nuno-agostinho** [comment]
Hi, @VincentGuyader, I just found out about your package and it seems really interesting. Are the aforementioned issues now fixed? Do you think this package could go to CRAN while supporting Windows, Mac and Linux? Thank you!
