### ISSUE TITLE
Notify from RStudio.app?

### ISSUE THREAD

**Issue by karthik** [gaborcsardi/notifier#3]
When I run:

```r
library(notifier)
notify(
  title = "15 Packages out of date",
  msg = c("You can run update.packages() to update them.",
  "Outdated packages: Boom colorspace desc memuse networkD3",
  "pbapply revealjs rgl rmdformats timevis and 5 more")
)
```

it launches a notification from R.app (which I don't use). Is there a way to make sure notification always originates from the source app?

**Comment by gaborcsardi** [comment]
Yeah, makes sense.

The source app is the command line `terminal-notifier`, so you don't want the source app, that would be a terminal app.

But I can check if it is issued from RStudio, and change the source app to that.
